### ISSUE TITLE
DOM.download doesn't work (in Firefox)

### ISSUE THREAD

**Issue by gka** [observablehq/notebook-stdlib#11]
clicking the download button in the sdtlib documentation notebook triggers console errors but no download
https://beta.observablehq.com/@mbostock/standard-library

![image](https://user-images.githubusercontent.com/617518/36449956-b728fdb8-168c-11e8-9b5c-c904571f070a.png)

**Comment by tmcw** [comment]
👍 Thanks for the bug report, Gregor! We've added `blob:` as a permitted protocol for `frame-src`, and that download button now works (in Firefox 59)
