### ISSUE TITLE
Override context.resetTransform in DOM.context2d?

### ISSUE THREAD

**Issue by mbostock** [observablehq/notebook-stdlib#16]
If you use DOM.context2d when *dpi* is not 1, you probably never want to say:

```js
context.resetTransform();
```

Instead you want to say

```js
context.resetTransform();
context.scale(dpi, dpi);
```

Do we want to monkey-patch *context*.resetTransform on the returned instance to do this automatically? Or is calling *context*.resetTransform considered user error?

**Comment by mootari** [comment]
resetTransform() should not be monkeypatched. I just ran into an issue with a multilayer canvas and drawImage() on HiDPI displays, where the dimensions passed to the output canvas' drawImage() would work as expected on Chrome in OSX, but would get scaled on Chrome in Windows 10. calling resetTransform() on the output canvas fixed the issue.
