### ISSUE TITLE
svg textPath is not working

### ISSUE THREAD

**Issue by fbreitwieser** [observablehq/notebook-stdlib#22]
Thanks for this great platform! Looking forward to working with it.

It seems that SVG textPath is not working in notebooks.

Minimal example: 
```
var svg = d3.select("svg"),
    width = +svg.attr("width"),
    height = +svg.attr("height");
  svg.append("defs").append("path").attr("id","p").attr("d","M 100 200 C 200 100 300 0 400 100 C 500 200 600 300 700 200");
  svg.append("use").attr("xlink:href", "#p").attr("fill", "none").attr("stroke","red");
  svg.append("text").append("textPath").attr("xlink:href", "#p").text("ASDASDASDASDSADSA");
```

Working on bl.ocks.org: https://bl.ocks.org/fbreitwieser/dd78384bc164051a728ba9c7231af962
Not working on observableHQ: https://beta.observablehq.com/d/3747228294b02e25

**Comment by tmcw** [comment]
Hi Florian,

Thanks! Mind posting this on [the forum](https://talk.observablehq.com/)? This repository is meant to be for the stdlib code only, and this issue report is about the notebook system itself.

- Tom

**Comment by mbostock** [comment]
You need to use a full URL due to the base href. :frown:

**Comment by fbreitwieser** [comment]
Will use the forum in the future. Thanks for the quick answers, and it seems you fixed it already. Thanks!
