### ISSUE TITLE
Allow deep-linking to cells

### ISSUE THREAD

**Issue by tiffon** [observablehq/notebook-stdlib#3]
It would be great if one could deep-link to individual cells:

https://beta.observablehq.com/@mbostock/five-minute-introduction#r140

(Doesn't look like this is presently possible, unless I missed it?)

Also, amazing work! :+1:

**Comment by mbostock** [comment]
Totally agreed! We are tracking this issue separately, so I’m going to close this issue but thank you for the suggestion.
