### ISSUE TITLE
using stdlib in custom webapp

### ISSUE THREAD

**Issue by aabes** [observablehq/notebook-stdlib#4]
I love the programing model and excellent blog post.
would be great to have ability to compose a notebook on https://beta.observablehq.com/, but then be able to ""export"" results into self hosted environment, where access to larger datasets and runtime environments is easier. 
In this model https://beta.observablehq.com/ is the "exploration and composition" platfrom, working on sample data, and the self hosted environment is the runtime.

The specific request here is:
  - demo / blog / instructions for leveraging stdlib in a self hosted env.

**Comment by jbouecke** [comment]
I like the way of thinking and writing notebooks using modern native web technologies also very much and would also like requesting the possibility to run such notebooks in a 'local' environment, especially possibly within a 'Browser Extension'!

So a serialized version of a notebook and an 'easy to use/install/start' local environment like a 'Browser Extension' would be a fantastic thing.

**Comment by tmcw** [comment]
Yep, serializing/exporting notebooks is high on our list and we've already got a prototype working. I added some more details in https://github.com/observablehq/notebook-stdlib/issues/25 and I'm closing this one to centralize discussion there, but feel free to post there with any other questions.
