### ISSUE TITLE
Adopt CommonMark?

### ISSUE THREAD

**Issue by mbostock** [observablehq/notebook-stdlib#52]
@tmcw writes: 

> Right now we're using [marked](https://github.com/chjj/marked) as a Markdown processor, and we simply document the syntax as Markdown. marked is modeled after the markdown.pl processor, rather than the CommonMark spec.
> 
> I think it'd be good for the future™ to commit to CommonMark syntax, as there are multiple commonmark-compliant parsers (commonmark.js, remarkable, markdown-it) with compatible syntax and output, and pointing to CommonMark as 'the syntax we support' is more rigorous than referring to the rather loose original Markdown description.

**Comment by mbostock** [comment]
I think the cat may already be out of the bag on this one. I expect quite a few notebooks are already using GFM features.

**Comment by tmcw** [comment]
Yeah, at this stage we can't break all those Markdown tables. A fix would be a bug at this point.
