### ISSUE TITLE
Add to KaTeX users

### ISSUE THREAD

**Issue by ylemkimon** [observablehq/notebook-stdlib#64]
Hey there, KaTeX maintainer here. Not really an issue. I'd like to ask if Observable would mind adding your logo to KaTeX user list? (https://github.com/Khan/KaTeX/pull/1569, preview availabe at https://deploy-preview-1569--katex.netlify.com/en/users.html) This is a really cool project! 😄

**Comment by mbostock** [comment]
Yes, we’re happy for our logo to be included in the list of KaTeX users! Thank you for KaTeX.

**Comment by ylemkimon** [comment]
@mbostock Thank you ❤️
