### ISSUE TITLE
A built-in for passing in data from the URL.

### ISSUE THREAD

**Issue by mbostock** [observablehq/notebook-stdlib#66]
It’d be nice if there were a way to encode information in the URL, say using the query string, and expose that information in the notebook. Currently the parent URL is not accessible to the notebook.

Maybe DOM.href would just be the URL in the address bar as a string?

**Comment by jashkenas** [comment]
I'm not sure how relevant the *whole* URL as a string would be to notebooks — but the queryString (ideally, parsed), and the fragment certainly would be.

Perhaps:

 * DOM.location.hash
 * DOM.location.search

... to mirror the window.location API?

**Comment by tmcw** [comment]
My gut here is... 😟I'm a little worried about making any part of the page URL accessible to the notebook. I totally see how it could be great for certain notebooks to embed / share data or something like that, but making the entire hash or querystring user-accessible sounds like it could make future UI changes tricky, like if we start using hashes to anchor people to inline comments, or the search portion of the UI to pin to a version in history.

Maybe we could only pass down a _part_ of the querystring? Or have some other well-defined subset of the location object that we could mark as 'in userspace' but be confident that it won't pwn future system features?

**Comment by mbostock** [comment]
The URL of a notebook is not a secret. I don’t see that hiding the current URL from the notebook buys us much, or conversely that exposing it overcommits. We could even pass through the window.location.search and window.location.hash to the iframe src directly, so that they work as-is within the worker iframe without a new built-in (though we’d want to prevent the query string from breaking the CDN cache).

That said, we could instead provide a more limited mechanism to pass data through the URL if desired.  Like, say, special-casing the `query` parameter, and exposing that as DOM.query. Then in `/@mbostock/my-notebook?query=foo`, DOM.query would be the string `"foo"`.

**Comment by aman-tiwari** [comment]
I would love to be able to get to the query string so that I could send people links to visualizations with certain notebook parameters filled in (for instance, as location hashes on a map, or parameters for a webgl vis).

**Comment by mbostock** [comment]
As discussed in [the most-recent changelog](https://beta.observablehq.com/@observablehq/changelog-2018-09-21), we’ve fixed the document’s base URL to include the query string. Strangely, there doesn’t seem to be a more obvious way to access the document’s base URL from JavaScript. The most concise way we’ve found is by constructing an A element, setting the href attribute to the empty string, then looking at the element’s search property (if you’re just interested in the query string):

```js
Object.assign(document.createElement("a"), {href: ""}).search
```

Or more concisely:

```js
html`<a href>`.search
```

This can then be passed to the URLSearchParams constructor, like so:

```js
new URLSearchParams(html`<a href>`.search)
```

You can see this in use in my [Function Plot notebook](https://beta.observablehq.com/@mbostock/function-plot?f=sin%28sin%28x%20*%20%28sin%28y%29%20-%20cos%28x%29%29%29%29%20-%20cos%28cos%28y%20*%20%28cos%28x%29%20-%20sin%28y%29%29%29%29).

**Comment by aman-tiwari** [comment]
Ah okay, thank you!

**Comment by simonw** [comment]
I have a use-case for this which isn't covered by the  ``html`<a href>`.search`` workaround.

I want to build a Notebook that uses client-side OAuth to authenticate against an API. The API I am using redirects back to my notebook like this:

https://beta.observablehq.com/d/6bd2b8b749afe254#token_type=Bearer&access_token=7230017A3E7D5B33A003250756

I'd like to be able to read the fragment hash (to get the token) and then store that token in localStorage.

This is a really nice way of working with APIs like this: because the access token is not passed in the querystring there is no chance of it accidentally ending up in a log file somewhere.

But... in order to do this, I need to be able to read the `#token_type=Bearer&access_token=...` bit that was passed in the URL.

**Comment by simonw** [comment]
I totally get @tmcw's concern above about wanting to preserve the # namespace for potential future Observable features.

Maybe whitelist `token_type` and `access_token`? That's a bit obscure though.

Better suggestion: define a reserved prefix (`obs.` or `_obs.` for example) and allow through everything else. So for the following URL:

https://beta.observablehq.com/d/6bd2b8b749afe254#token_type=Bearer&access_token=7230017A3E7D5B33A003250756&obs.commentref=923449734

The notebook could access `DOM.location.hash` and would get back this string:

`token_type=Bearer&access_token=7230017A3E7D5B33A003250756`

With the `obs.commentref=923449734` bit stripped out.
