### ISSUE TITLE
Shortcuts to run a cell block

### ISSUE THREAD

**Issue by aaronlelevier** [observablehq/notebook-stdlib#70]
Hi,

I was trying out the Observable online notebooks. They're pretty cool.

I wanted to give some feedback. I use Jupyter notebook a lot, and it has key bindings for "run cell and go to next cell" which is shift+enter. If you want to run the current cell and insert a new cell below, then it's option+enter.  I was looking for some key binding shortcuts like this. Do they exist?

Maybe if they are the same key bindings as Jupyter notebook, then the users feel more natural about running the notebooks, since the key bindings are the same.

Just sharing my feedback.  Great product, and excited to see where you go with it.

Thanks

**Comment by jashkenas** [comment]
Hi Aaron,

This isn't really the right place to discuss key bindings (we have [a forum](https://talk.observablehq.com/) for that sort of thing), but in short, shift+enter runs the current cell, and option+enter splits the current cell, focusing the new cell below.

Here's a full list:

![image](https://user-images.githubusercontent.com/4732/46835940-7a796580-cd64-11e8-82b6-9e02b0304b5f.png)

You can also see it by typing `?` on any notebook page...

**Comment by mbostock** [comment]
Please see this forum thread for a discussion regarding keyboard shortcuts:

https://talk.observablehq.com/t/list-of-keyboard-shortcuts/89

Here are the current (macOS) keyboard shortcuts:

<img width="499" alt="screen shot 2018-10-11 at 2 46 06 pm" src="https://user-images.githubusercontent.com/230541/46835928-6f263a00-cd64-11e8-8b21-ad94bb26c463.png">

Shift-Enter is also used by Observable to run the current cell. But unlike Jupyter, we have a [dataflow runtime](https://beta.observablehq.com/@mbostock/how-observable-runs), so you don’t typically want to run cells sequentially—when you run one cell, any cell that depends on that cell is run automatically and instantly.

Likewise, we use Option-Enter to split the current cell, which, if the caret is already at the end of the cell, is equivalent to inserting a new cell below the current cell. The “run cell” happens automatically whenever you commit a change to the code, including after you split or merge. You rarely need to run cells manually, though you can Shift-Enter or click the play button for that.

**Comment by aaronlelevier** [comment]
Thank you for clarifying and also saying about the discussion forum. I understand better now. Thanks.
