### ISSUE TITLE
Fix cell left side actions display

### ISSUE THREAD

**Issue by VinceValence** [observablehq/notebook-stdlib#74]
Hello,

In some displays, such as in my asus zenbook's 13.3'' display or the one of my samsung galaxy s8+,  the left side actions (the plus sign to create a new cell, the arrow to show or hide a cell, and the pin to pin cells) are almost hidden and are very difficult to click or tap

**Comment by mbostock** [comment]
Hi Vicente! Thanks for the feedback. If you want to discuss the user interface, please head over to our forums: https://talk.observablehq.com/

We’re aware of some of the current user interface limitations on small screens and are working to improve the design. (On very small screens, you can click the blue pencil icon in the bottom-right corner to cause the left margin to slide out for easier clicking.)

**Comment by VinceValence** [comment]
Thank you very much for your quick reply. I'll go to the forum. Thanks for
the workaround!
