### ISSUE TITLE
asciimath template literal

### ISSUE THREAD

**Issue by anandthakker** [observablehq/notebook-stdlib#8]
This only occurred to me because because #7 said:

> Since the Viz.js dependency is lazily loaded this would be a very small addition to the stdlib

[Asciimath](http://asciimath.org/) is pretty great when I'm typing quick math and I don't feel like going all-in on Latex.  It's roughly, "type math the way you would in your code or your TI-83 calculator".

```js
asciimath = {
   const amToTex = await require('https://wzrd.in/standalone/asciimath-to-latex/');
   return function(strings, ...args) {
       return tex(strings.map(amToTex), ...args.map(amToTex));
   };
}
```

Then again, `Viz.js` is surely a much more stable dependency than `asciimath-to-latex`, and `dot\`\`` adds a totally new dimension of functionality whereas this is just a variation, so understood if you simply close with prejudice.

**Comment by anandthakker** [comment]
https://beta.observablehq.com/@anandthakker/ascii-math

**Comment by mbostock** [comment]
Thanks for the suggestion, Anand. Our current plan is to try to keep the stdlib small, so we’re going to stick with KaTeX/LaTeX for now. But as you discovered you can always require/import from npm or another notebook to use something outside of stdlib as you prefer.
